### ISSUE TITLE
Function previewxml$() not found

### ISSUE THREAD

**Issue by softwarefailure** [SamuraiCrow/RapaEdit#1]
When opening test.rapa, selecting "window win0" and then "Preview" from the menu, there is this error message:

![image](https://user-images.githubusercontent.com/6772528/174278618-82db49b3-adde-4fdb-8183-5a8d337e2d06.png)

**Comment by SamuraiCrow** [comment]
@softwarefailure 
Thanks for the bug report!

**Comment by TelemarRosenberger** [comment]
Hallo SamuraiCrow
I mean its in "Local xml$=pnl"
just can't find the error :-( 
You program is really a quick help and should be further developed!

**Comment by SamuraiCrow** [comment]
FWIW, I might update my MorphOS box sometime next week and do some tinkering with Hollywood 9.1 but there are other, bigger problems I am trying to solve such as a friend being rendered homeless.

As a hint, the codebase is object-oriented so the missing function is likely related to the included window.hws file not finding a child method from any gadgets in the window.  The call site is not the problem.

**Comment by TelemarRosenberger** [comment]
Ok SamuraiCrow
I hope you find it ;-)

**Comment by SamuraiCrow** [comment]
@TelemarRosenberger , I hope YOU find it.  It was supposed to be an example program to demonstrate object oriented programming and modular code.  Both are advanced techniques!

Off-topic:
Do you post on the forum on [Hollywood-MAL.com](https://forum.hollywood-mal.com)?  I had a post in the RapaGUI category about how this program was written!

**Comment by SamuraiCrow** [comment]
Found that the bug only happens on a loaded file.  Starting a new application and adding a window doesn't recrate the bug.  It's got to be a bug in the load/save routines.  (Posting this message to GitHub using the Wayfarer browser in MorphOS 3.17, BTW!)

**Comment by SamuraiCrow** [comment]
Since the Save routine has to remove all the methods from the cloned table, adding the methods back in is definitely part of the load function.  It's probably just missing one line of code for the previewxml$ method to be added back into the window.

**Comment by SamuraiCrow** [comment]
Solved!  When the load subroutine was being invoked, the method names were assigned case-sensitive but method names are stored all lowercase when Hollywood generates them.
